on:
  push:
    paths:
      - apim/**
    branches:
      - main
  workflow_dispatch:

name: Build and Release API Repo

jobs:
  release_repo:
    name: Release Repo
    uses: kariyasinghe-cell/wso2-workflows/.github/workflows/release-apim-api.yml@main
    secrets: inherit
